apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: w40k-duel
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: europe-west1-docker.pkg.dev/w40k-468120/containers/w40k-duel:latest
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
  traffic:
    - latestRevision: true
      percent: 100
